# NumPy

## Installing NumPy

In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\HP\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [8]:
import numpy as np


In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([[2,4], [3,7]]'asl')
z = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print(y)    
print(z)

[1 2 3 4 5]
[[2 4]
 [3 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
